
-- Drop tables if they exist (in reverse dependency order)
DROP TABLE IF EXISTS account_clients;
DROP TABLE IF EXISTS savings_accounts;
DROP TABLE IF EXISTS mortgage_accounts;
DROP TABLE IF EXISTS business_checking_accounts;
DROP TABLE IF EXISTS regular_checking_accounts;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS banks;


-- 1. Create banks table
CREATE TABLE banks (
    bank_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bank_number INT NOT NULL UNIQUE,
    bank_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create accounts table (base table for inheritance)
CREATE TABLE accounts (
    account_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_number INT NOT NULL UNIQUE,
    account_type VARCHAR(50) NOT NULL,
    date_opened DATE NOT NULL,
    bank_id INT NOT NULL,
    balance DECIMAL(15,2) NOT NULL DEFAULT 20.00,
    manager_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bank_id) REFERENCES banks(bank_id)
);

-- 3. Create regular_checking_accounts table
CREATE TABLE regular_checking_accounts (
    account_id BIGINT PRIMARY KEY,
    credit_limit DECIMAL(15,2) NOT NULL,
    profit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
);

-- 4. Create business_checking_accounts table
CREATE TABLE business_checking_accounts (
    account_id BIGINT PRIMARY KEY,
    credit_limit DECIMAL(15,2) NOT NULL,
    business_revenue DECIMAL(15,2) NOT NULL,
    profit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    management_fee DECIMAL(15,2) NOT NULL DEFAULT 1000.00,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
);

-- 5. Create mortgage_accounts table
CREATE TABLE mortgage_accounts (
    account_id BIGINT PRIMARY KEY,
    original_mortgage_amount DECIMAL(15,2) NOT NULL,
    monthly_payment DECIMAL(15,2) NOT NULL,
    years INT NOT NULL,
    profit DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    management_fee DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
);

-- 6. Create savings_accounts table
CREATE TABLE savings_accounts (
    account_id BIGINT PRIMARY KEY,
    deposit_amount DECIMAL(15,2) NOT NULL,
    years INT NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
);

-- 7. Create clients table
CREATE TABLE clients (
    client_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    rank_value INT NOT NULL CHECK (rank_value >= 0 AND rank_value <= 10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Create account_clients linking table
CREATE TABLE account_clients (
    account_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    association_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_id, client_id),
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES clients(client_id) ON DELETE CASCADE
);


-- Insert bank data
INSERT INTO banks (bank_number, bank_name) VALUES
(1, 'First National Bank');

-- Insert clients data (12 clients to have variety)
INSERT INTO clients (name, rank_value) VALUES
('Alice Johnson', 10),
('Bob Smith', 8),
('Carol Davis', 10),
('David Wilson', 7),
('Emma Brown', 9),
('Frank Miller', 10),
('Grace Lee', 6),
('Henry Taylor', 10),
('Isabel Garcia', 8),
('Jack Anderson', 10),
('Kate Martinez', 9),
('Liam Thompson', 5);

-- Insert base accounts data
INSERT INTO accounts (account_number, account_type, date_opened, bank_id, balance, manager_name) VALUES
-- Regular Checking Accounts
(1, 'Regular Checking Account', '2024-01-15', 1, 20.00, 'Manager A'),
(2, 'Regular Checking Account', '2024-01-16', 1, 20.00, 'Manager A'),
(3, 'Regular Checking Account', '2024-01-17', 1, 20.00, 'Manager A'),
(4, 'Regular Checking Account', '2024-01-18', 1, 20.00, 'Manager A'),
-- Business Checking Accounts
(5, 'Business Checking Account', '2024-02-01', 1, 20.00, 'Manager B'),
(6, 'Business Checking Account', '2024-02-02', 1, 20.00, 'Manager B'),
(7, 'Business Checking Account', '2024-02-03', 1, 20.00, 'Manager B'),
(8, 'Business Checking Account', '2024-02-04', 1, 20.00, 'Manager B'),
-- Mortgage Accounts
(9, 'Mortgage Account', '2024-03-01', 1, 20.00, 'Manager C'),
(10, 'Mortgage Account', '2024-03-02', 1, 20.00, 'Manager C'),
(11, 'Mortgage Account', '2024-03-03', 1, 20.00, 'Manager C'),
(12, 'Mortgage Account', '2024-03-04', 1, 20.00, 'Manager C'),
-- Savings Accounts
(13, 'Savings Account', '2024-04-01', 1, 20.00, 'Manager D'),
(14, 'Savings Account', '2024-04-02', 1, 20.00, 'Manager D'),
(15, 'Savings Account', '2024-04-03', 1, 20.00, 'Manager D'),
(16, 'Savings Account', '2024-04-04', 1, 20.00, 'Manager D');

-- Insert regular checking accounts specific data
INSERT INTO regular_checking_accounts (account_id, credit_limit, profit) VALUES
(1, 5000.00, 500.00),
(2, 7500.00, 750.00),
(3, 10000.00, 1000.00),
(4, 6000.00, 600.00);

-- Insert business checking accounts specific data
INSERT INTO business_checking_accounts (account_id, credit_limit, business_revenue, profit, management_fee) VALUES
(5, 15000.00, 12000000.00, 0.00, 1000.00),
(6, 20000.00, 8000000.00, 5000.00, 1000.00),
(7, 25000.00, 15000000.00, 0.00, 1000.00),
(8, 18000.00, 6000000.00, 4800.00, 1000.00);

-- Insert mortgage accounts specific data
INSERT INTO mortgage_accounts (account_id, original_mortgage_amount, monthly_payment, years, profit, management_fee) VALUES
(9, 250000.00, 2000.00, 15, 1333.33, 25000.00),
(10, 350000.00, 2800.00, 20, 1400.00, 35000.00),
(11, 180000.00, 1500.00, 10, 1440.00, 18000.00),
(12, 420000.00, 3200.00, 25, 1344.00, 42000.00);

-- Insert savings accounts specific data
INSERT INTO savings_accounts (account_id, deposit_amount, years) VALUES
(13, 10000.00, 5),
(14, 25000.00, 3),
(15, 50000.00, 10),
(16, 15000.00, 7);

-- Insert account-client associations (2 clients per account)
INSERT INTO account_clients (account_id, client_id) VALUES
(1, 1), (1, 2),
(2, 3), (2, 4),
(3, 5), (3, 6),
(4, 7), (4, 8),
(5, 9), (5, 10),
(6, 11), (6, 12),
(7, 1), (7, 3),
(8, 2), (8, 4),
(9, 5), (9, 7),
(10, 6), (10, 8),
(11, 9), (11, 11),
(12, 10), (12, 12),
(13, 1), (13, 5),
(14, 2), (14, 6),
(15, 3), (15, 7),
(16, 4), (16, 8);